---
group_size: 10
parliament:
    SPD: 206
    GRUENE: 118
    FDP: 92
    CDU_CSU: 197
    AfD: 83
    SSW: 1
    LINKE: 39
parliament_majority: 369
required_consensus: 0.8
parties: ["SPD", "CDU_CSU", "GRUENE", "FDP"]
data_path: "data/data_wide.csv"
---
